//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalloonRss.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalloonRss.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon ico_blue16 {
            get {
                object obj = ResourceManager.GetObject("ico_blue16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_orange16 {
            get {
                object obj = ResourceManager.GetObject("ico_orange16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_yellow16 {
            get {
                object obj = ResourceManager.GetObject("ico_yellow16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_yellow32 {
            get {
                object obj = ResourceManager.GetObject("ico_yellow32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing link attribute in config file.
        /// </summary>
        internal static string str_balloonErrorChannelLinkTag {
            get {
                return ResourceManager.GetString("str_balloonErrorChannelLinkTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mandatory &quot;channel&quot; tag..
        /// </summary>
        internal static string str_balloonErrorConfigChannelTag {
            get {
                return ResourceManager.GetString("str_balloonErrorConfigChannelTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start BalloonRSS because the program is already running..
        /// </summary>
        internal static string str_balloonErrorDuplicateInstanceBody {
            get {
                return ResourceManager.GetString("str_balloonErrorDuplicateInstanceBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting BalloonRSS.
        /// </summary>
        internal static string str_balloonErrorDuplicateInstanceHeader {
            get {
                return ResourceManager.GetString("str_balloonErrorDuplicateInstanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the RSS feed from .
        /// </summary>
        internal static string str_balloonErrorParseRss {
            get {
                return ResourceManager.GetString("str_balloonErrorParseRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during retrieving .
        /// </summary>
        internal static string str_balloonErrorRetrieving {
            get {
                return ResourceManager.GetString("str_balloonErrorRetrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RSS entry in queue yet..
        /// </summary>
        internal static string str_balloonWarningNoEntryBody {
            get {
                return ResourceManager.GetString("str_balloonWarningNoEntryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display full RSS entry.
        /// </summary>
        internal static string str_balloonWarningNoEntryHeader {
            get {
                return ResourceManager.GetString("str_balloonWarningNoEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access the program by right clicking on this application icon. You should start by adding the RSS channels of your choice..
        /// </summary>
        internal static string str_balloonWelcomeBody {
            get {
                return ResourceManager.GetString("str_balloonWelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to BalloonRSS.
        /// </summary>
        internal static string str_balloonWelcomeHeader {
            get {
                return ResourceManager.GetString("str_balloonWelcomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear collected data.
        /// </summary>
        internal static string str_channelContextMenuClearData {
            get {
                return ResourceManager.GetString("str_channelContextMenuClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all read.
        /// </summary>
        internal static string str_channelContextMenuMarkRead {
            get {
                return ResourceManager.GetString("str_channelContextMenuMarkRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Channel Information.
        /// </summary>
        internal static string str_channelFormTitle {
            get {
                return ResourceManager.GetString("str_channelFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Rate.
        /// </summary>
        internal static string str_channelHeaderClickRate {
            get {
                return ResourceManager.GetString("str_channelHeaderClickRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mess. Queued.
        /// </summary>
        internal static string str_channelHeaderCount {
            get {
                return ResourceManager.GetString("str_channelHeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eff. Prio..
        /// </summary>
        internal static string str_channelHeaderEffPrio {
            get {
                return ResourceManager.GetString("str_channelHeaderEffPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string str_channelHeaderLastUpdate {
            get {
                return ResourceManager.GetString("str_channelHeaderLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Prio..
        /// </summary>
        internal static string str_channelHeaderPrio {
            get {
                return ResourceManager.GetString("str_channelHeaderPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string str_channelHeaderTitle {
            get {
                return ResourceManager.GetString("str_channelHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mess. Channel.
        /// </summary>
        internal static string str_channelHeaderTotal {
            get {
                return ResourceManager.GetString("str_channelHeaderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the RSS channel .
        /// </summary>
        internal static string str_channelSettingsConfirmDeleteText {
            get {
                return ResourceManager.GetString("str_channelSettingsConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion of RSS channel.
        /// </summary>
        internal static string str_channelSettingsConfirmDeleteTitel {
            get {
                return ResourceManager.GetString("str_channelSettingsConfirmDeleteTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rss.slashdot.org/Slashdot/slashdot.
        /// </summary>
        internal static string str_channelSettingsDefault1Link {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string str_channelSettingsDefault1Priority {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault1Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/technology/rss.xml.
        /// </summary>
        internal static string str_channelSettingsDefault2Link {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string str_channelSettingsDefault2Priority {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault2Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string str_channelSettingsDefault3Link {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string str_channelSettingsDefault3Priority {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault3Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string str_channelSettingsDefault4Link {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault4Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string str_channelSettingsDefault4Priority {
            get {
                return ResourceManager.GetString("str_channelSettingsDefault4Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit RSS Channel Settings.
        /// </summary>
        internal static string str_channelSettingsEditFormTitle {
            get {
                return ResourceManager.GetString("str_channelSettingsEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string str_channelSettingsFormDeleteButton {
            get {
                return ResourceManager.GetString("str_channelSettingsFormDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string str_channelSettingsFormEditButton {
            get {
                return ResourceManager.GetString("str_channelSettingsFormEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string str_channelSettingsFormNewButton {
            get {
                return ResourceManager.GetString("str_channelSettingsFormNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Channel Settings.
        /// </summary>
        internal static string str_channelSettingsFormTitle {
            get {
                return ResourceManager.GetString("str_channelSettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string str_channelSettingsHeaderPriority {
            get {
                return ResourceManager.GetString("str_channelSettingsHeaderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string str_channelSettingsHeaderTitle {
            get {
                return ResourceManager.GetString("str_channelSettingsHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal format of RSS link: .
        /// </summary>
        internal static string str_channelSettingsIllegalLink {
            get {
                return ResourceManager.GetString("str_channelSettingsIllegalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Channel &amp;Information.
        /// </summary>
        internal static string str_contextMenuChannelInfo {
            get {
                return ResourceManager.GetString("str_contextMenuChannelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS &amp;Channel Settings.
        /// </summary>
        internal static string str_contextMenuChannelSettings {
            get {
                return ResourceManager.GetString("str_contextMenuChannelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string str_contextMenuExit {
            get {
                return ResourceManager.GetString("str_contextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retrieve RSS Channels.
        /// </summary>
        internal static string str_contextMenuGetChannels {
            get {
                return ResourceManager.GetString("str_contextMenuGetChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message &amp;History.
        /// </summary>
        internal static string str_contextMenuHistory {
            get {
                return ResourceManager.GetString("str_contextMenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Last Message.
        /// </summary>
        internal static string str_contextMenuLastMessage {
            get {
                return ResourceManager.GetString("str_contextMenuLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next Message.
        /// </summary>
        internal static string str_contextMenuNextMessage {
            get {
                return ResourceManager.GetString("str_contextMenuNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &amp;Settings.
        /// </summary>
        internal static string str_contextMenuSettings {
            get {
                return ResourceManager.GetString("str_contextMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Message History.
        /// </summary>
        internal static string str_historyFormTitle {
            get {
                return ResourceManager.GetString("str_historyFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string str_historyHeaderChannel {
            get {
                return ResourceManager.GetString("str_historyHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string str_historyHeaderId {
            get {
                return ResourceManager.GetString("str_historyHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed at.
        /// </summary>
        internal static string str_historyHeaderTimestamp {
            get {
                return ResourceManager.GetString("str_historyHeaderTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string str_historyHeaderTitle {
            get {
                return ResourceManager.GetString("str_historyHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  RSS messages pending..
        /// </summary>
        internal static string str_iconInfoNewsCount {
            get {
                return ResourceManager.GetString("str_iconInfoNewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 RSS message pending..
        /// </summary>
        internal static string str_iconInfoNewsCount1 {
            get {
                return ResourceManager.GetString("str_iconInfoNewsCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BalloonRSS paused..
        /// </summary>
        internal static string str_iconInfoPause {
            get {
                return ResourceManager.GetString("str_iconInfoPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan to display balloon pop-up [s].
        /// </summary>
        internal static string str_settingsBalloonTimespan {
            get {
                return ResourceManager.GetString("str_settingsBalloonTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use channel name as pop-up title.
        /// </summary>
        internal static string str_settingsChannelAsTitle {
            get {
                return ResourceManager.GetString("str_settingsChannelAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel configuration filename.
        /// </summary>
        internal static string str_settingsChannelConfigFilename {
            get {
                return ResourceManager.GetString("str_settingsChannelConfigFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for application updates.
        /// </summary>
        internal static string str_settingsCheckForUpdates {
            get {
                return ResourceManager.GetString("str_settingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority influence of message clicks (prio &lt;-&gt; clicks).
        /// </summary>
        internal static string str_settingsClickInfluence {
            get {
                return ResourceManager.GetString("str_settingsClickInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between displaying two RSS messages [s].
        /// </summary>
        internal static string str_settingsDisplayIntervall {
            get {
                return ResourceManager.GetString("str_settingsDisplayIntervall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retriever intervall has to be larger than the display intervall..
        /// </summary>
        internal static string str_settingsErrorRetrieveSmallerDisplay {
            get {
                return ResourceManager.GetString("str_settingsErrorRetrieveSmallerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value greater than valid maximum .
        /// </summary>
        internal static string str_settingsErrorValueToLarge {
            get {
                return ResourceManager.GetString("str_settingsErrorValueToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value smaller than valid minimum .
        /// </summary>
        internal static string str_settingsErrorValueToSmall {
            get {
                return ResourceManager.GetString("str_settingsErrorValueToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string str_settingsFormCancelButton {
            get {
                return ResourceManager.GetString("str_settingsFormCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming application settings change.
        /// </summary>
        internal static string str_settingsFormErrorHeader {
            get {
                return ResourceManager.GetString("str_settingsFormErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string str_settingsFormOKButton {
            get {
                return ResourceManager.GetString("str_settingsFormOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BalloonRSS Settings.
        /// </summary>
        internal static string str_settingsFormTitle {
            get {
                return ResourceManager.GetString("str_settingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of entries in message history.
        /// </summary>
        internal static string str_settingsHistoryDepth {
            get {
                return ResourceManager.GetString("str_settingsHistoryDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall for retrieving new RSS messages [s].
        /// </summary>
        internal static string str_settingsRetrieveIntervall {
            get {
                return ResourceManager.GetString("str_settingsRetrieveIntervall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in pause mode.
        /// </summary>
        internal static string str_settingsStartPaused {
            get {
                return ResourceManager.GetString("str_settingsStartPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this message to read the release notes. To disable this message deactivate the update check in the application settings..
        /// </summary>
        internal static string str_updateBody {
            get {
                return ResourceManager.GetString("str_updateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of BalloonRSS available: .
        /// </summary>
        internal static string str_updateTitle {
            get {
                return ResourceManager.GetString("str_updateTitle", resourceCulture);
            }
        }
    }
}
