//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalloonRss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalloonRss.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon ico_blue16 {
            get {
                object obj = ResourceManager.GetObject("ico_blue16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_orange16 {
            get {
                object obj = ResourceManager.GetObject("ico_orange16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_yellow16 {
            get {
                object obj = ResourceManager.GetObject("ico_yellow16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_yellow32 {
            get {
                object obj = ResourceManager.GetObject("ico_yellow32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string str_balloonErrorHeader {
            get {
                return ResourceManager.GetString("str_balloonErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RSS entry in queue yet..
        /// </summary>
        internal static string str_balloonWarningNoEntryBody {
            get {
                return ResourceManager.GetString("str_balloonWarningNoEntryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display full RSS entry.
        /// </summary>
        internal static string str_balloonWarningNoEntryHeader {
            get {
                return ResourceManager.GetString("str_balloonWarningNoEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string str_contextMenuExit {
            get {
                return ResourceManager.GetString("str_contextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message &amp;History.
        /// </summary>
        internal static string str_contextMenuHistory {
            get {
                return ResourceManager.GetString("str_contextMenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Last Message.
        /// </summary>
        internal static string str_contextMenuLastMessage {
            get {
                return ResourceManager.GetString("str_contextMenuLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next Message.
        /// </summary>
        internal static string str_contextMenuNextMessage {
            get {
                return ResourceManager.GetString("str_contextMenuNextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string str_contextMenuSettings {
            get {
                return ResourceManager.GetString("str_contextMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Message History.
        /// </summary>
        internal static string str_historyFormTitle {
            get {
                return ResourceManager.GetString("str_historyFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string str_historyHeaderId {
            get {
                return ResourceManager.GetString("str_historyHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string str_historyHeaderTitle {
            get {
                return ResourceManager.GetString("str_historyHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BalloonRSS initialized..
        /// </summary>
        internal static string str_iconInfoInit {
            get {
                return ResourceManager.GetString("str_iconInfoInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  RSS messages pending..
        /// </summary>
        internal static string str_iconInfoNewsCount {
            get {
                return ResourceManager.GetString("str_iconInfoNewsCount", resourceCulture);
            }
        }
    }
}
